version: '3.8'
services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - 3000:3000
      - 5000:5000
      - 2376:2376
    command: --storage-driver overlay2

  jenkins-blueocean:
    build:
      context: .
      dockerfile: Dockerfile
    image: myjenkins-blueocean:2.426.3-1
    container_name: jenkins-blueocean
    restart: on-failure
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - ./jenkins-home:/home
    ports:
      - 8080:8080
      - 50000:50000
    depends_on:
      - jenkins-docker

  ubuntu18-agent:
    build:
      context: ./node-agent
      dockerfile: Dockerfile
    container_name: ubuntu18-agent
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 5005:22
      - 8000:8000
    networks:
      - jenkins


networks:
  jenkins:
    name: jenkins

volumes:
  jenkins-docker-certs:
  jenkins-data:
